### ISSUE TITLE
pycsp.parallel ossocket.py: struct.error: argument for 's' must be a bytes object

### ISSUE THREAD

**Issue by Tratoschek** [runefriborg/pycsp#28]
If the hostname maps to 127.* under the function _get_interface_ip is called and fails under python3:

```
Traceback (most recent call last):
  File "./csp-factorial.py", line 39, in <module>
    chan1 = Channel()
  File "/usr/lib64/python3.4/site-packages/pycsp/parallel/channel.py", line 154, in __init__
    p,_ = getThreadAndName()
  File "/usr/lib64/python3.4/site-packages/pycsp/parallel/const.py", line 74, in getThreadAndName
    init()
  File "/usr/lib64/python3.4/site-packages/pycsp/parallel/process.py", line 444, in init
    dispatch = SocketDispatcher().getThread()
  File "/usr/lib64/python3.4/site-packages/pycsp/parallel/dispatch.py", line 91, in __new__
    return cls.getInstance(cls, *args, **kargs)
  File "/usr/lib64/python3.4/site-packages/pycsp/parallel/dispatch.py", line 133, in getInstance
    cls.__instance.socketthreaddata = SocketThreadData(cls.__instance.condObj)
  File "/usr/lib64/python3.4/site-packages/pycsp/parallel/dispatch.py", line 403, in __init__
    self.server_socket, self.server_addr = ossocket.start_server(addr)
  File "/usr/lib64/python3.4/site-packages/pycsp/parallel/ossocket.py", line 155, in start_server
    address = (_get_ip(), address[1])
  File "/usr/lib64/python3.4/site-packages/pycsp/parallel/ossocket.py", line 46, in _get_ip
    ip = _get_interface_ip(ifname)
  File "/usr/lib64/python3.4/site-packages/pycsp/parallel/ossocket.py", line 35, in _get_interface_ip
    struct.pack('256s', ifname[:15])
struct.error: argument for 's' must be a bytes object
```
With the following script I could reproduce the error:
```
#!/usr/bin/env python3

import socket, os, struct, fcntl

def _get_interface_ip(ifname):
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    print(type(ifname[:15]))
    ip = socket.inet_ntoa(fcntl.ioctl(
            s.fileno(),
            0x8915,  # SIOCGIFADDR
            struct.pack('256s', ifname[:15])
            )[20:24])
    s.close()
    return ip

def _get_ip():
    ip = socket.gethostbyname(socket.gethostname())
    if ip.startswith("127.") and os.name != "nt":
        interfaces = ["eth0","eth1","eth2","wlan0","wlan1","wifi0","ath0","ath1","ppp0"]
        for ifname in interfaces:
            try:
                ip = _get_interface_ip(ifname)
                break;
            except IOError:
                pass
    return ip

print(_get_ip())
```
Replacing `struct.pack('256s', ifname[:15])` with `struct.pack('256s', ifname[:15].encode('utf-8'))` fixes the error for me both with Python2 and 3.

**Comment by Tratoschek** [comment]
Fix in the actual file:
```
diff --git a/pycsp/parallel/ossocket.py b/pycsp/parallel/ossocket.py
index 36281bd..43c3b4e 100644
--- a/pycsp/parallel/ossocket.py
+++ b/pycsp/parallel/ossocket.py
@@ -32,7 +32,7 @@ if os.name != "nt":
         ip = socket.inet_ntoa(fcntl.ioctl(
                 s.fileno(),
                 0x8915,  # SIOCGIFADDR
-                struct.pack('256s', ifname[:15])
+                struct.pack('256s', ifname[:15].encode('utf-8'))
                 )[20:24])
         s.close()
         return ip
```

**Comment by sleepymurph** [comment]
I experienced this same issue with Python 3.5 on Ubuntu 16.04 LTS (xenial).

I'd like to point out that pull request #29 also fixes this bug. Plus it will correctly find the IP address on newer systemd Linux systems (like Ubuntu 15.04 and up) that use [a new network interface naming scheme]( https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/) and do not have the classic "eth0", "eth1", etc. It does however add a dependency on the [netifaces]( https://pypi.python.org/pypi/netifaces) library.
